# ruby encoding: utf-8
Localidad.delete_all
Localidad.create( localidad: "Aaron Castellanos", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Acebal", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Aguara", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Albarellos", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Alcorta", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Aldao", region_educativa: "V", nodo: "ROSARIO", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Aldao", region_educativa: "V", nodo: "SANTA FE", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Alejandra", region_educativa: "III", nodo: "RECONQUISTA", departamento: "San Javier", es_sede_provincial: "")
Localidad.create( localidad: "Alvarez", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Alvear", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Ambrosetti", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Amenábar", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Andino", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Angelica", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Angeloni", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Arequito", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Arminda", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Armstrong", region_educativa: "V", nodo: "ROSARIO", departamento: "Belgrano", es_sede_provincial: "")
Localidad.create( localidad: "Arocena", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Arroyo Aguiar", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Arroyo Ceibal", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Arroyo Leyes", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Arroyo Seco", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Arrufo", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Arteaga", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Ataliva", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Aurelia", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Avellaneda", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Barrancas", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Bauer y Sigel", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Bella Italia", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Berabevu", region_educativa: "V", nodo: "VENADO TUERTO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Berna", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Bernardo de Irigoyen", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Bicha", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Bigand", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Bigand", region_educativa: "V", nodo: "ROSARIO", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Bombal", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Bossi", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Bouquet", region_educativa: "VIII", nodo: "ROSARIO", departamento: "Belgrano", es_sede_provincial: "")
Localidad.create( localidad: "Bustinza", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Cabal", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Cacique Ariacariquin", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Javier", es_sede_provincial: "")
Localidad.create( localidad: "Cafferata", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Calchaqui", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Campo Andino", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Campo Garay", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Candioti", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Cañada de Gómez", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Cañada del Ucle", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Cañada Ombú", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Cañada Rica", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Cañada Rosquín", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Capitán Bermúdez", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Capivara", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Carcarañá", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Carlos Pellegrini", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Carmen", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Carmen del Sauce", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Carreras", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Carrizales", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Casalegno", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Casas", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Casilda", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Castelar", region_educativa: "VIII", nodo: "RAFAELA", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Castellanos", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Gato Colorado", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Cavour", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Cayasta", region_educativa: "IV", nodo: "SANTA FE", departamento: "Garay", es_sede_provincial: "")
Localidad.create( localidad: "Cayastacito", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Cello", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Centeno", region_educativa: "V", nodo: "ROSARIO", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Cepeda", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Ceres", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Chabas", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Chañar Ladeado", region_educativa: "V", nodo: "VENADO TUERTO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Chapuy", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Chovet", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Christophersen", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Clason", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Clucellas", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Ana", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Belgrano", region_educativa: "VIII", nodo: "RAFAELA", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Dolores", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Dos Rosas y la Legua", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Duran", region_educativa: "II", nodo: "RECONQUISTA", departamento: "San Javier", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Mascia", region_educativa: "IV", nodo: "SANTA FE", departamento: "Garay", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Rosa", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Colonia Silva", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Constanza", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Coronda", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Coronel Arnold", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Coronel Bogado", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Coronel Dominguez", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Coronel Fraga", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Correa", region_educativa: "VI", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Crispi", region_educativa: "VIII", nodo: "RAFAELA", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Cululu", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Curupayti", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Desvio Arijon", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Díaz", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Diego de Alvear", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Egusquiza", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "El Araza", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "El Rabon", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "El Sombrerito", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "El Trébol", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Elisa", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Elortondo", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Emilia", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Empalme San Carlos", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Empalme Villa Constitución", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Esmeralda", region_educativa: "VIII", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Esperanza", region_educativa: "III", nodo: "RAFAELA", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Estación Clucellas", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Esteban Rams", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Esther", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Eustolia", region_educativa: "V", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Felicia", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Fidela", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Fighiera", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Florencia", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Fortín Olmos", region_educativa: "I", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Franck", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Fray Luis Beltrán", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Frontera", region_educativa: "VIII", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Fuentes", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Funes", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Gaboto", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Galisteo", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Gálvez", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Garabato", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Garibaldi", region_educativa: "VIII", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "General Gelly", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "General Lagos", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Gessler", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Gobernador Crespo", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Godeken", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Godoy", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Golondrina", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Granadero Baigorria", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Gregoria Perez de Denis", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Grutly", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Guadalupe Norte", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Helvecia", region_educativa: "IV", nodo: "SANTA FE", departamento: "Garay", es_sede_provincial: "")
Localidad.create( localidad: "Hersilia", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Hipatia", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Huanqueros", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Hugentobler", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Hughes", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Humberto 1", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Humboldt", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Ibarlucea", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Ingeniero Chanourdie", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Intiyaco", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Irigoyen", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Iturraspe", region_educativa: "V", nodo: "ROSARIO", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Ituzaingó", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Jacinto L. Arauz", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Josefina", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Juan B. Molina", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Juncal", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "La Braza", region_educativa: "II", nodo: "RECONQUISTA", departamento: "San Javier", es_sede_provincial: "")
Localidad.create( localidad: "La Cabral", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "La Camila", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "La Chispa", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "La Clara", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "La Criolla", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "La Gallareta", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "La Lucila", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "La Pelada", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "La Penca", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "La Rubia", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "La Sarita", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "La Vanguardia", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Labordeboy", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Laguna Paiva", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Landeta", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Lanteri", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Larrechea", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Las Avispas", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Las Bandurrias", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Las Garzas", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Las Palmeras", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Las Parejas", region_educativa: "V", nodo: "ROSARIO", departamento: "Belgrano", es_sede_provincial: "")
Localidad.create( localidad: "Las Petacas", region_educativa: "VIII", nodo: "RAFAELA", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Las Rosas", region_educativa: "V", nodo: "ROSARIO", departamento: "Belgrano", es_sede_provincial: "")
Localidad.create( localidad: "Las Toscas", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Las Tunas", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Lazzarino", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Lehmann", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Llambi Campbell", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Logroño", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Loma Alta (V. Tramontini)", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Lopez", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Los Amores", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Los Cardones", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Los Quirquinchos", region_educativa: "V", nodo: "VENADO TUERTO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Los Laureles", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Los Molinos", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Lucio V. Lopez", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Luis Palacios (La Salada)", region_educativa: "V", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Maciel", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Maggiolo", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Malabrigo", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Marcelino Escalada", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Margarita", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Margarita", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "María Juana", region_educativa: "VIII", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "María Luisa", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "María Susana", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "María Teresa", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Marini", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Matilde", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Maua", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Maximo Paz", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Melincue", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Miguel Torres", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Moises Ville", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Monigotes", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Monje", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Monte Obscuridad", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Monte Vera", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Montefiore", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Montes de Oca", region_educativa: "V", nodo: "ROSARIO", departamento: "Belgrano", es_sede_provincial: "")
Localidad.create( localidad: "Murphy", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Nare", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Nelson", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Nicanore E. Molinas", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Nuevo Torino", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Ñanducita", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Oliveros", region_educativa: "IV", nodo: "SANTA FE", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Palacios", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Pavon", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Pavon Arriba", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Pedro Gómez Cello", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Perez", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Peyrano", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Piaggio", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "Piamonte", region_educativa: "VIII", nodo: "ROSARIO", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Pilar", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Piñero", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Postugalete", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Pozo Borrado", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Presidente Roca", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Progreso", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Providencia", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Pueblo Esther", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Pueblo Muñoz", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Puerto General San Martín", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Pujato", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Pujato Norte", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Rafaela", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Ramayon", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Ramona", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Raquel", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Reconquista", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Recreo", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Ricardone", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Rivadavia", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Roldán", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Romang", region_educativa: "II", nodo: "RECONQUISTA", departamento: "San Javier", es_sede_provincial: "")
Localidad.create( localidad: "Rosario", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario", es_sede_provincial: "")
Localidad.create( localidad: "Rueda", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Rufino", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Sa Pereira", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Saguier", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Saladero M. Cabal", region_educativa: "IV", nodo: "SANTA FE", departamento: "Garay", es_sede_provincial: "")
Localidad.create( localidad: "Salto Grande", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "San Agustín", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Antonio", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "San Antonio de Obligado", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "San Bernardo", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "San Bernardo", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "San Carlos Centro", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Carlos Norte", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Carlos Sud", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Cristóbal", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "San Eduardo", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "San Eugenio", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "San Fabián", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "San Francisco de Santa Fe", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "San Genaro", region_educativa: "V", nodo: "ROSARIO", departamento: "San Jerónimo", es_sede_provincial: "")
Localidad.create( localidad: "San Gregorio", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "San Guillermo", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "San Javier", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Javier", es_sede_provincial: "")
Localidad.create( localidad: "San Jerónimo del Sauce", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Jerónimo Norte", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Jéronimo Sur", region_educativa: "V", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "San Jorge", region_educativa: "VIII", nodo: "RAFAELA", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "San Jose", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "San José", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Jose de la Esquina", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "San Jose del Rincón", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "San Justo", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "San Lorenzo", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "San Maríano", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "San Martín de las Escobas", region_educativa: "VIII", nodo: "RAFAELA", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "San Martín Norte", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "San Vicente", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Sancti Spiritu", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Sanford", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Santa Clara de Buena Vista", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Santa Clara de Saguier", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Santa Eusebia", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Santa Fe", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital", es_sede_provincial: "")
Localidad.create( localidad: "Santa Isabel", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Santa Margarita", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Santa María Centro", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Santa María Norte", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Santa Rosa", region_educativa: "IV", nodo: "SANTA FE", departamento: "Garay", es_sede_provincial: "")
Localidad.create( localidad: "Santa Teresa", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Santo Domingo", region_educativa: "IV", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Santo Tomé", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Santurce", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Sargento Cabral", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Sarmiento", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Sastre Traill", region_educativa: "VIII", nodo: "RAFAELA", departamento: "San Martín", es_sede_provincial: "")
Localidad.create( localidad: "Sauce Viejo", region_educativa: "IV", nodo: "SANTA FE", departamento: "La Capital (campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Serodino", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Soldini", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Soledad", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Soutomayor", region_educativa: "III", nodo: "SANTA FE", departamento: "Las Colonias", es_sede_provincial: "")
Localidad.create( localidad: "Suardi", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Sunchales", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Susana", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Tacuarendi", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Tacurales", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Tacurales", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Tartagal", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Teodelina", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Theobald", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Timbúes", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Toba", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Tortugas", region_educativa: "V", nodo: "ROSARIO", departamento: "Belgrano", es_sede_provincial: "")
Localidad.create( localidad: "Tostado", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Totoras", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Uranga", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Venado Tuerto", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Vera", region_educativa: "II", nodo: "RECONQUISTA", departamento: "Vera", es_sede_provincial: "")
Localidad.create( localidad: "Vera y Pintado", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Videla", region_educativa: "IV", nodo: "SANTA FE", departamento: "San Justo", es_sede_provincial: "")
Localidad.create( localidad: "Vila", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Villa Amelia", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Villa Ana", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Villa Cañas", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Villa Constitución", region_educativa: "VI", nodo: "ROSARIO", departamento: "Constitución", es_sede_provincial: "")
Localidad.create( localidad: "Villa Eloisa", region_educativa: "V", nodo: "ROSARIO", departamento: "Iriondo", es_sede_provincial: "")
Localidad.create( localidad: "Villa Gobernador Gálvez", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Villa Guillermina", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Villa Minetti", region_educativa: "I", nodo: "RAFAELA", departamento: "9 de Julio", es_sede_provincial: "")
Localidad.create( localidad: "Villa Mugueta", region_educativa: "VI", nodo: "ROSARIO", departamento: "San Lorenzo", es_sede_provincial: "")
Localidad.create( localidad: "Villa Ocampo", region_educativa: "II", nodo: "RECONQUISTA", departamento: "General Obligado", es_sede_provincial: "")
Localidad.create( localidad: "Villa Saralegui", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Villa Trinidad", region_educativa: "IX", nodo: "RAFAELA", departamento: "San Cristóbal", es_sede_provincial: "")
Localidad.create( localidad: "Villada", region_educativa: "V", nodo: "ROSARIO", departamento: "Caseros", es_sede_provincial: "")
Localidad.create( localidad: "Virginia", region_educativa: "III", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
Localidad.create( localidad: "Wheelwright", region_educativa: "VII", nodo: "VENADO TUERTO", departamento: "General Lopez", es_sede_provincial: "")
Localidad.create( localidad: "Zavalla", region_educativa: "VI", nodo: "ROSARIO", departamento: "Rosario (Campaña)", es_sede_provincial: "")
Localidad.create( localidad: "Zenon Pereyra", region_educativa: "VIII", nodo: "RAFAELA", departamento: "Castellanos", es_sede_provincial: "")
